#!/usr/bin/env bash
# Generates a Go source file that inlines a tarball as base64-encoded bytes.
# The generated file decodes the data into a []byte var at program init.
# This avoids //go:embed path issues with Bazel's sandbox: genrule outputs live
# in bazel-out/... while static sources live in the workspace root; rules_go's
# compilepkg rejects //go:embed when source files span both directories.
#
# Arch is resolved from --arch if provided, then $GOARCH, then uname -m.
# Bazel passes --arch explicitly; `go generate` relies on $GOARCH.
#
# Usage: ./scripts/generate-embed-go.sh \
#   --output /path/to/embed.go \
#   --tarball /path/to/clp-s_linux_*.tar.gz \
#   [--arch amd64|arm64]

set -o errexit
set -o nounset
set -o pipefail

output=""
tarball=""
arch_flag=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --output)  output="$2";    shift 2 ;;
        --tarball) tarball="$2";   shift 2 ;;
        --arch)    arch_flag="$2"; shift 2 ;;
        --help)    echo "Usage: $0 --output FILE --tarball TAR.GZ [--arch amd64|arm64]"; exit 0 ;;
        *)         echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [[ -z "${output}" || -z "${tarball}" ]]; then
    echo "ERROR: --output and --tarball are required" >&2
    exit 1
fi

if [[ ! -f "${tarball}" ]]; then
    echo "ERROR: Tarball not found: ${tarball}" >&2
    exit 1
fi

# Resolve arch: --arch flag > $GOARCH env var > uname -m.
case "${arch_flag:-${GOARCH:-$(uname -m)}}" in
    amd64|x86_64|k8) arch=amd64 ;;
    arm64|aarch64)   arch=arm64 ;;
    *) echo "ERROR: Unsupported arch: ${arch_flag:-${GOARCH:-$(uname -m)}}. Use --arch amd64|arm64." >&2; exit 1 ;;
esac

encoded="$(base64 < "${tarball}" | tr -d '\n')"

# No explicit //go:build tag: the filename (embed_linux_amd64.go /
# embed_linux_arm64.go) carries an implicit OS+arch build constraint recognised
# by both go build and Bazel's rules_go. The stub's explicit build tag
# excludes it on linux/{amd64,arm64} to avoid a duplicate Data declaration.
{
    printf 'package clp\n\n'
    printf 'import "encoding/base64"\n\n'
    printf '// Data holds the embedded clp-s tarball for linux/%s.\n' "${arch}"
    printf '// Auto-generated by generate-embed-go.sh — do not edit.\n'
    printf '//\n'
    printf '// The filename (embed_linux_%s.go) carries an implicit OS+arch build\n' "${arch}"
    printf '// constraint, so this file is compiled only on linux/%s. embed_linux_stub.go\n' "${arch}"
    printf '// has an explicit build tag that excludes it on the same platforms, preventing\n'
    printf '// a duplicate Data declaration.\n'
    printf 'var Data []byte\n\n'
    printf 'func init() {\n'
    printf '\tb, err := base64.StdEncoding.DecodeString(_clpEmbeddedData)\n'
    printf '\tif err != nil {\n'
    printf '\t\tpanic("clp: embedded data corrupted: " + err.Error())\n'
    printf '\t}\n'
    printf '\tData = b\n'
    printf '}\n\n'
    printf 'const _clpEmbeddedData = `%s`\n' "${encoded}"
} > "${output}"

size_bytes="$(wc -c < "${tarball}" | tr -d ' ')"
echo "Generated: ${output} (${size_bytes} bytes tarball)"
